apiVersion: 1
contactPoints:
  - orgId: 1
    name: oncall
    receivers:
      - uid: slack
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          title: "Grafana Alert"
          text: "{{ .CommonAnnotations.summary }}"
          recipient: "#alerts"

notificationPolicies:
  - orgId: 1
    receiver: oncall
    group_by: [alertname]

policies:
  - orgId: 1
    receiver: oncall

# Rule group example (Web Vitals LCP p75 > 4s for 5m)
groups:
  - orgId: 1
    name: UX Rules
    folder: "General"
    interval: 1m
    rules:
      - uid: lcp-high
        title: "LCP p75 too high"
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: histogram_quantile(0.75, sum by(le)(rate(web_vitals_lcp_seconds_bucket[5m])))
              intervalMs: 60000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: 4
              intervalMs: 60000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: "LCP p75 above 4s"
        labels:
          severity: warning
