apiVersion: 1

# Prometheus (metrics)
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # Loki (logs)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  # Umami Postgres (visitor analytics)
  - name: Umami-Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600

  # OpenReplay ClickHouse (sessions)
  - name: OpenReplay-ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: default
      xAxisMode: time
      httpMethod: POST

  # Uptime Kuma (metrics via Prometheus endpoint)
  - name: Kuma-Prom
    type: prometheus
    access: proxy
    url: http://uptime-kuma:3001/metrics
    editable: true
